### ISSUE TITLE
Redirects can break metadata lookups on Connect

### ISSUE THREAD

**Issue by colearendt** [rstudio/pins-r#759] opened 2023-07-31 19:28 UTC
We recently migrated our internal Connect server to a new URL and set up a redirect from old -> new.

Pins _mostly_ handles this OK, but returned some invalid metadata that generated error messages like:

```
Error: Can't find version '400657'
```

Basically, `pin_versions()` seemed to return an array of versions that was not necessarily associated with the pin in question

Slack thread with details: https://positpbc.slack.com/archives/C03DK5MJW6S/p1690668801613589?thread_ts=1690667853.301989&cid=C03DK5MJW6S

@jspiewak

**Comment by machow** [comment] 2023-07-31 21:19
Is there any chance you could get the version of pins that produced this error? One quick thought is that changing the server url fixed it, and that would also create a new cache.

**Comment by jspiewak** [comment] 2023-07-31 21:26
See the Slack thread. I fetched the versions for several of the pins.

**Comment by machow** [comment] 2023-07-31 21:53
Ah, sorry--that was bad phrasing on my part. I meant to say-- what was the version of the pins package you were using? 😅

**Comment by jspiewak** [comment] 2023-08-01 15:54
Unfortunately not able to reproduce at the moment, and it is possible this was before updating to latest `pins` version (1.2.0).

**Comment by juliasilge** [comment] 2023-08-07 17:47
I'm definitely interested in any details that could help reproduce this! Seeing what you got from `pin_versions()` is pretty mystifying to me.

**Comment by juliasilge** [comment] 2023-08-30 20:27
Related to the problems that came up during our internal Connect server migration, we now have these merged in: 

- #770 
- #771 

Still to do is deal with:

- #776 
- #763 

According to my notes from our small retro on the migration, I believe this is all we can currently reproduce so I'm going to close this issue about those _bananas_ 🍌 problems with the metadata. Please feel free to reopen or make a new issue if we have something more to work with on problems we observed!

**Closed by juliasilge** 2023-08-30 20:27 UTC
